packages:
  - "packages/*"
  - "packages/*/*"
  - "packages-sizes/*"
  - "packages-sizes/*/*"
  - "examples/*"
  - "website"
catalogs:
  "tseslint7":
    "@typescript-eslint/eslint-plugin": "^7.16.1"
    "@typescript-eslint/parser": "^7.16.1"
    "@typescript-eslint/rule-tester": "^7.16.1"
    "@typescript-eslint/scope-manager": "^7.16.1"
    "@typescript-eslint/type-utils": "^7.16.1"
    "@typescript-eslint/types": "^7.16.1"
    "@typescript-eslint/utils": "^7.16.1"
    "typescript-eslint": "^7.16.1"
  "tseslint8":
    "@typescript-eslint/eslint-plugin": "rc-v8"
    "@typescript-eslint/parser": "rc-v8"
    "@typescript-eslint/rule-tester": "rc-v8"
    "@typescript-eslint/scope-manager": "rc-v8"
    "@typescript-eslint/type-utils": "rc-v8"
    "@typescript-eslint/types": "rc-v8"
    "@typescript-eslint/utils": "rc-v8"
    "typescript-eslint": "rc-v8"
