packages:
  - "packages/*"
  - "packages/*/*"
  - "examples/*"
  - "website"
catalogs:
  "tseslint7":
    "@typescript-eslint/eslint-plugin": "7.15.0"
    "@typescript-eslint/parser": "7.15.0"
    "@typescript-eslint/rule-tester": "7.15.0"
    "@typescript-eslint/scope-manager": "7.15.0"
    "@typescript-eslint/type-utils": "7.15.0"
    "@typescript-eslint/types": "7.15.0"
    "@typescript-eslint/utils": "7.15.0"
    "typescript-eslint": "7.15.0"
  "tseslint8":
    "@typescript-eslint/eslint-plugin": "rc-v8"
    "@typescript-eslint/parser": "rc-v8"
    "@typescript-eslint/rule-tester": "rc-v8"
    "@typescript-eslint/scope-manager": "rc-v8"
    "@typescript-eslint/type-utils": "rc-v8"
    "@typescript-eslint/types": "rc-v8"
    "@typescript-eslint/utils": "rc-v8"
    "typescript-eslint": "rc-v8"
