name: Test
on:
    push:
        branches:
            - main
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 20.8.0
            - name: Install bun
              uses: oven-sh/setup-bun@v1
              id: bun-install
              with:
                  bun-version: latest
            - name: Install dependencies
              run: bun i
            - name: Build library
              run: bun run build
            - name: Run tests
              run: bun run test
